version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password